name: Frontend Asset Build Pipeline
run-name: Build Frontend Assets
on: [push]
jobs:
  build-frontend-assets:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get update && apt-get install -y podman
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./build-frontend.sh
      - uses: actions/upload-artifacts@v3
        with:
          name: frontend
          path: js/
