name: Frontend Asset Build Pipeline
run-name: Build Frontend Assets
on: [push]
jobs:
  build-frontend-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.2.0
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version-file: '../package.json'
      - run: yarn action-build
      - uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: js/
