name: Frontend Asset Build Pipeline
run-name: Build Frontend Assets
on: [push]
jobs:
  build-frontend-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./build-frontend.sh
      - uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: js/
